name: motores_musicos
description: Flutter app to control motores via HM-10 BLE
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^6.1.0
  provider: ^6.0.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
